AMPA-250-DataForPathIntroPage
dinosysOrg/masterclass-web pull request #21
Opened 2017-07-26 08:25 UTC by hpb0412

+ Populate data for Path Intro page
+ Prepare flow for path fetching
+ Fix issues related to SSR
+ Add mock data

2017-07-26 09:10 UTC, nhatdev1193 requested changes

2017-07-26 09:10 UTC, nhatdev1193 commented on server/index.dev.js
> +        <script src="/assets/js/bundle.js"></script>
@hpb0412 sao phai them ``` / ``` vay a ?

2017-07-26 09:10 UTC, nhatdev1193 commented on src/redux/path/epic.js
> +  // );
@hpb0412 sao a lai commit ca code bi comment :disappointed:

2017-07-26 09:10 UTC, nhatdev1193 commented on src/spec/mockdata/path.json
> +        "id": 9,
covention spaces la 2, cai nay la 4 roi a, a setup lai trong vs code.

2017-07-26 10:14 UTC, hpb0412 commented on src/spec/mockdata/path.json
> +        "id": 9,
@nhatdev1193: chắc github display bị lỗi. File gốc của anh vẫn là 2 space. Anh xài github cũng bị mấy lần vậy rồi.

2017-07-26 10:14 UTC, hpb0412 commented on src/redux/path/epic.js
> +  // );
@nhatdev1193 : cái task này expect phải có backend api mà backend chưa có nên phải mock data. Mà mock data không thôi thì đâu có simulate đc cái async khi phải đợi load data từ server. => anh comment cái code đó và thay bằng cái ở dưới. Sau này ra backend rồi thì delete cái ở dưới rồi uncomment thôi. => vậy cho tiện. Trước sau gì thì cái file này cũng phải edit khi integrate backend => làm cách này sau này tiện hơn thôi.

2017-07-26 10:16 UTC, hpb0412 commented on server/index.dev.js
> +        <script src="/assets/js/bundle.js"></script>
@nhatdev1193: ah, để chỉ rõ là link từ root.

2017-07-27 03:35 UTC, hpb0412 commented on src/spec/mockdata/path.json
> +        "id": 9,
@nhatdev1193 : anh sẽ replace file ở dưới local rồi push lên xem có fix được không

2017-07-27 08:41 UTC, nhatdev1193 approved these changes

2017-07-31 03:16 UTC, votheduy154 approved these changes

2017-07-31 03:23 UTC, merged