Feature/login auth
dinosysOrg/masterclass-web pull request #22
Opened 2017-07-26 12:52 UTC by votheduy154

2017-08-08 04:35 UTC, ndduy requested changes

2017-08-08 04:35 UTC, ndduy commented on src/app.js
> +    this.state = {};
ko co j sao add?

2017-08-08 04:35 UTC, ndduy commented on src/components/header/header.js
> +          <li><a href="#" onClick={()=>this.props.userAction.signOut()}>Đăng xuất</a></li>
Implement luon localization duoc ko

https://github.com/yahoo/react-intl

2017-08-09 10:06 UTC, nhatdev1193 commented on src/components/header/header.js
> +          <li><a href="#" onClick={()=>this.props.userAction.signOut()}>Đăng xuất</a></li>
@ndduy already implemented in  [https://github.com/dinosysOrg/masterclass-web/pull/24/commits/7f151e4326acfbe08beaecf92a7b8f0e14da759d](url)

2017-08-09 10:32 UTC, nhatdev1193 approved these changes

2017-08-09 10:32 UTC, merged