init project
dinosysOrg/masterclass-web pull request #3
Opened 2017-07-11 03:39 UTC by nhatdev1193

2017-07-11 03:49 UTC, hpb0412 approved these changes
Ok!

2017-07-11 03:57 UTC, ndduy requested changes

2017-07-11 03:57 UTC, ndduy commented on .eslintcache
> +{"/home/sin/Desktop/masterclass-web/webpack.config.js":{"size":803,"mtime":1499711458788,"hashOfConfig":"15ydj73","results":{"filePath":"/home/sin/Desktop/masterclass-web/webpack.config.js","messages
This should be added to gitignore

2017-07-11 03:57 UTC, ndduy commented on .gitignore
> +yarn-error.log*
Use this as an example

https://github.com/github/gitignore/blob/master/Node.gitignore

2017-07-11 07:05 UTC, votheduy154 reviewed
oke

2017-07-11 07:09 UTC, votheduy154 approved these changes

2017-07-11 08:14 UTC, ndduy commented
Tại sao add vào gitignore rồi mà file đấy vẫn có trong commit??

2017-07-12 03:32 UTC, ndduy approved these changes

2017-07-12 03:32 UTC, merged