add components for 'path progress summary'
dinosysOrg/masterclass-web pull request #4
Opened 2017-07-12 08:00 UTC by hpb0412

code formatted using vscode plugins to follow eslint rule!

2017-07-12 08:22 UTC, hpb0412 commented
Hi all, the mark "All checks have failed" is due to unfinished Jenkins configuration! Thanks!

2017-07-12 11:01 UTC, ndduy requested changes
Nhân tiện ví dụ này, anh muốn hỏi, trường hợp nào mình chỉ dùng props bình thường, trường hợp nào mình lưu vao redux state

2017-07-13 09:25 UTC, nhatdev1193 commented
@ndduy theo e biet, thi nhung cai nao lien quan den xu ly data nhu loading data tu server, thay doi trang thai cua du lieu thi minh luu vao state. Con ko thi cu react ma xai thoi a.

2017-07-13 10:47 UTC, ndduy commented
Nếu như thế thì trong trường hợp này information thì phải nhét vào trong redux đúng không.

Thế thì @hpb0412 sửa lại

2017-07-13 11:14 UTC, votheduy154 commented
em nghĩ trong trường hợp này nên tạo 1 cái data giả dạng object rồi fetch data đó vào trong component, để sau này có api trả về lấy ra nó cũng nhanh hơn.

2017-07-13 11:17 UTC, nhatdev1193 commented
@ndduy dung roi a, nhung hien tai minh chua implement redux vao, nen e nghi a Khoa dag hard code nen nhu vay, 
@hpb0412 theo e a chi thiet ke component nhu the nao thoi, nhung ji can thong tin tu server thi a de mock data, sau nay co api thi implement nguoc lai.

2017-07-13 15:58 UTC, hpb0412 commented
@ndduy: hi anh, như @nhatdev1193 đã nói thì em đang hard code một vài số liệu. Các component hiện tại rất basic, mình build nó focus cho mục địch presentation. Sau này khi mình apply redux thì mình chỉ việc wrap các component này vào các container là xong.

@ndduy: cho câu hỏi về props thì @nhatdev1193 đã nói cũng đúng. Em chỉ bổ sung thêm như thế này: component thường lấy data và behavior từ props, kể cả redux state muốn dùng thì phải truyền vào component thông qua props.

2017-07-14 04:05 UTC, ndduy commented
ok tam thoi approve, khi nao implement xong redux tinh tiep

2017-07-14 04:05 UTC, ndduy approved these changes

2017-07-14 04:05 UTC, merged