edit router path
dinosysOrg/masterclass-web pull request #43
Opened 2017-09-08 01:51 UTC by votheduy154

2017-09-09 17:32 UTC, nhatdev1193 requested changes

2017-09-09 17:32 UTC, nhatdev1193 commented on src/app.js
> +            <Route key="/Overview" path="/Path/:id/Overview" render={() => this.checkAuthenticate(Overview)} />
@votheduy154 cai nay chac minh dinh nghia them router cho path,
```
<Route path='/paths' >
  <Route path='/paths/:path_Id' component={overview} />
  <Route path='/paths/:path_Id/sylabus' component={sylabus} />
</Route>
```

2017-09-10 16:00 UTC, votheduy154 commented on src/app.js
> +            <Route key="/Overview" path="/Path/:id/Overview" render={() => this.checkAuthenticate(Overview)} />
v4 nó bỏ cái nested rồi em, 1 là sài switch bao ở ngoaì, 2 là viêt dạng function, a thay viet kieu nay cung dc ne

2017-09-11 07:44 UTC, nhatdev1193 requested changes

2017-09-11 07:44 UTC, nhatdev1193 commented on src/containers/path/path.js
> +          <Link to="/Path/Overview">go to over view</Link>
cai nay ``` <Link to="/Path/:path_id/Overview"> ```

2017-09-12 04:43 UTC, nhatdev1193 approved these changes

2017-09-12 04:43 UTC, merged