Implement Video Player UI, intergrate play, pause, forward, backward
dinosysOrg/masterclass-web pull request #45
Opened 2017-09-08 10:53 UTC by nghiep9523

- Done styling controller and 3-video layout.

- Play, pause, forward, backward can be used now

- Layout setting popup implemented

2017-09-09 17:37 UTC, nhatdev1193 requested changes

2017-09-09 17:37 UTC, nhatdev1193 commented on src/containers/path/path.js
> +        <VideoPlayer />
cai ``` < VideoPlayer /> ``` minh se implement trong sylabus page nen @nghiep9523 co gi e xoa dong nay di nha  😄  neu de demo thi nen xoa truoc khi commit 😄

2017-09-11 02:18 UTC, nghiep9523 commented on src/containers/path/path.js
> +        <VideoPlayer />
oke anh :smile:

2017-09-11 11:37 UTC, nhatdev1193 requested changes

2017-09-11 11:37 UTC, nhatdev1193 commented on src/components/shared/video_player.js
> +      this.setState({speedOpened: !this.state.speedOpened});
them set state cho cai setting layout, de no tat luc openSpeedControl va nguoc lai.

2017-09-11 11:37 UTC, nhatdev1193 commented on src/containers/path/path.js
> +import VideoPlayer from '../../components/shared/video_player';
xoa cai nay di nha e

2017-09-11 11:38 UTC, nhatdev1193 requested changes

2017-09-11 11:38 UTC, nhatdev1193 commented on src/components/shared/video_player.js
> +          'http://via.placeholder.com/215x105',
e contact vs Minh ben Design de xin may cai hinh cua layout roi edit cai nay lai.

2017-09-12 05:29 UTC, nhatdev1193 approved these changes

2017-09-12 07:51 UTC, votheduy154 approved these changes

2017-09-12 07:51 UTC, merged