Feature/implement api mypath
dinosysOrg/masterclass-web pull request #63
Opened 2017-09-21 11:34 UTC by votheduy154

2017-09-22 00:34 UTC, nhatdev1193 requested changes

2017-09-22 00:34 UTC, nhatdev1193 commented on src/containers/myPath/myPath.js
>                  <li className="page-item active"><a className="page-link" href="">1</a></li>
comment khuc nay la sao a ?

2017-09-22 00:34 UTC, nhatdev1193 commented on src/containers/myPath/myPath.js
>    { subject: 'Skill 1', A: 120, B: 110, fullMark: 150 },
cai data nay minh remove di a, get data tu api tra ve thi dung cai ham cua e de show skill

2017-09-22 00:34 UTC, nhatdev1193 commented on src/containers/myPath/myPath.container.js
> +          {...this.state}
sao lai ``` {...this.state}} ```o day a?

2017-09-22 01:50 UTC, votheduy154 commented on src/containers/myPath/myPath.js
>                  <li className="page-item active"><a className="page-link" href="">1</a></li>
api chua du nen anh commnet de do

2017-09-22 01:52 UTC, votheduy154 commented on src/containers/myPath/myPath.container.js
> +          {...this.state}
cho nay co cai remove path, anh truyen redux vao state, khi remove thi no cap nhat trang thai delete luon, ko phai loading lai trang

2017-09-22 01:59 UTC, nhatdev1193 commented on src/containers/myPath/myPath.js
>                  <li className="page-item active"><a className="page-link" href="">1</a></li>
cai khuc nay la phan trang fai ko a? https://github.com/AdeleD/react-paginate a dung thang nay, api chi tra ve cai array da sort roi, minh se phan trang.

2017-09-22 02:49 UTC, votheduy154 commented on src/containers/myPath/myPath.container.js
> +          {...this.state}
ah anh nhin nham, bua de state o ngoai h chuyen vo trong, de anh xoa :))

2017-09-22 02:52 UTC, votheduy154 commented on src/containers/myPath/myPath.js
>    { subject: 'Skill 1', A: 120, B: 110, fullMark: 150 },
api chua fix em, dang doi fix

2017-09-22 02:53 UTC, nhatdev1193 commented on src/containers/myPath/myPath.js
>                  <li className="page-item active"><a className="page-link" href="">1</a></li>
cai nay phan trang fai ko a? a dung https://www.npmjs.com/package/react-paginate de phan trang, tai api tra ve cai array da sort thoi.

2017-09-26 11:18 UTC, nhatdev1193 approved these changes

2017-09-26 11:18 UTC, merged